### ISSUE TITLE
Where is movie2idx come from？

### ISSUE THREAD

**Issue by giser-yugang** [acetherace/my-movie-recommender#3]
I saw code in tfidf-tag-data.ipynb:

```
with open('../../data/movie_to_idx.pkl', 'rb') as handle:
    movie2idx = pickle.load(handle)
```

Where is movie2idx come from？Which file generates it？

**Comment by umesh46** [comment]
I have the same question. How do we create this file "movie_to_idx.pkl'' ?

**Comment by alineberry** [comment]
Whatever code created a file with that name must have gotten lost somehow. I can however tell you what `movie2idx` is and point you to code that creates it.

`movie2idx` is a dictionary mapping the native Movie ID's from GroupLens to a sequence of indices in {0, 1, ..., n_movies-1}. These are used to index into embedding matrices, hence the need for a continuous sequence of ints starting at 0. 

Here is the code to create the mapping:
```python
m_uniq = ratings.movieId.unique()
movie2idx = {o:i for i,o in enumerate(m_uniq)}
```
https://github.com/alineberry/my-movie-recommender/blob/master/notebooks/movie_similarity/neural-net-movie-embedding.ipynb

**Comment by koushikgoodur** [comment]
After reviewing your code content and collaborative similarity .ipynb 
get_detailed_recs(lotr, collaborative_embeddings, '../../data/collaborative_recs_lotr.csv')
get_detailed_recs(lotr, content_embeddings, '../../data/content_recs_lotr.csv')
get_ensemble_recs(lotr, content_embeddings, collaborative_embeddings, '../../data/ensemble_recs_lotr.csv')

Could you kindly inform me about the source of these CSV files? Also, would it be possible for you to share all the CSV files with me? Thank you.
